version: 2
updates:
  - package-ecosystem: "pip"
    directory: "frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "backend"
    schedule:
      interval: "weekly"
